exports.emails = [
  {
    id: 1,
    subject: "test email 1",
    sender: "Mr Terry",
    reciever: "Player",
    dateTime: "3:05 12th Jan",
    body: "Hello this is an email yos",
    suspicious: false,
  },

  {
    id: 2,
    subject: "test email 2",
    sender: "Mr Dad",
    reciever: "Player",
    dateTime: "3:15 12th Jan",
    body: "Hello this is an email for the children",
    suspicious: false,
  },

  {
    id: 3,
    subject: "sus test email 3",
    sender: "Mr Rond",
    reciever: "Player",
    dateTime: "5:37 12th Jan",
    body: "Hello this is an email for the big boys that want to get into crypto Hello this is an email for the big boys that want to get into crypto Hello this is an email for the big boys that want to get into crypto Hello this is an email for the big boys that want to get into crypto Hello this is an email for the big boys that want to get into crypto",
    suspicious: true,
  },
  {
    id: 4,
    subject: "sus test email 3",
    sender: "Mr Rond",
    reciever: "Player",
    dateTime: "5:37 12th Jan",
    body: "Hello this is an email for the big boys that want to get into crypto",
    suspicious: true,
  },
  {
    id: 5,
    subject: "sus test email 3",
    sender: "Mr Rond",
    reciever: "Player",
    dateTime: "5:37 12th Jan",
    body: "Hello this is an email for the big boys that want to get into crypto",
    suspicious: true,
  },

  {
    id: 6,
    subject: "test email 4",
    sender: "Mr Ruty",
    reciever: "Player",
    dateTime: "7:05 12th Jan",
    body: "Hello this is an email yos for my son",
    suspicious: false,
  },
  {
    id: 7,
    subject: "test email 4",
    sender: "Mr Ruty",
    reciever: "Player",
    dateTime: "7:05 12th Jan",
    body: "Hello this is an email yos for my son",
    suspicious: false,
  },
  {
    id: 8,
    subject: "test email 4",
    sender: "Mr Ruty",
    reciever: "Player",
    dateTime: "7:05 12th Jan",
    body: "Hello this is an email yos for my son",
    suspicious: false,
  },
  {
    id: 9,
    subject: "test email 4",
    sender: "Mr Ruty",
    reciever: "Player",
    dateTime: "7:05 12th Jan",
    body: "Hello this is an email yos for my son",
    suspicious: false,
  },
  {
    id: 10,
    subject: "test email 4",
    sender: "Mr Ruty",
    reciever: "Player",
    dateTime: "7:05 12th Jan",
    body: "Hello this is an email yos for my son",
    suspicious: false,
  },
];
